#!/usr/bin/env python
########
# 
#  ktest - Klondike Protocol Test Utility
# 
# (C) Copyright 2013 Chris Savery. 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# main.c - main USB cmd loop and dispatch for Klondike mining firmware
#
#/
import sys, serial
from struct import *

workid = addr = 0
midstate = "6969696969696969696969696969696969696969696969696969696969696969"
merkle = "696969696969696969696969"

def kopen(dev='/dev/Klondike'):
	global ser
	try:
		return serial.Serial(dev, 115200, timeout=0.1)
	except serial.SerialException, e:
		print "Cannot connect to /dev/Klondike"
		sys.exit(1)

def sendcmd(cmd, data=""):
	global ser, addr
	try:
		ser.write(cmd + chr(addr) + data)
	except serial.SerialException, e:
		ser = kopen()
		ser.write(cmd + chr(addr) + data)
	data = ser.read(16)
	if cmd in 'WASED':
		print "State:%c, ASICs:%u, Slaves:%u, WorkQ:%u, Current WorkID:%x, Temp:%u, Fan:%u, HashCount:%u, ErrCount:%u" % unpack("=cBBBBBBHH", data[2:])
	elif cmd == 'C':
		print "Clock:%d, Target Temp:%u, Critical Temp:%u, Target Fan: %u" % unpack("=HBBB", data[2:])
	elif cmd == 'I':
		print "Version:%x, Serial#:%x, ProductID: %s" % unpack("=BL8s", data[2:])
	else:
		print ' '.join(x.encode('hex') for x in data)

if __name__ == '__main__':
	
	ser = kopen()
	print ser.name
	sendcmd('I')

	while True: 
		cmd = raw_input("Cmds [WAISCE.Q]: ").upper()
		if cmd == "":
			continue
		data = ""
		if cmd == 'Q':
			break
		elif cmd =='.':
			addr = raw_input("Target Address: ")
			if addr == "":
				addr = 0
			addr = int(addr)
			print "Address changed to ", addr
			continue
		elif cmd == 'C':
			clk = raw_input("Clock (or blank for query only): ")
			if clk != "":
				data = pack("=H", int(clk))
				data += pack("=B", int(raw_input("Target Temp: ")))
				data += pack("=B", int(raw_input("Critical Temp: ")))
				data += pack("=B", int(raw_input("Target Fan: ")))
			else:
				data = chr(0)
		elif cmd == 'E':
			data = raw_input("1 (enable) or 0 (disable): ")
		elif cmd in 'WA':
			workid = (workid+1) % 256
			data = chr(workid) + midstate.decode('hex') + merkle.decode('hex')
		
		sendcmd(cmd, data)

	ser.close()	
